// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package template

import (
	"time"

	audit2 "notification-platform/internal/event/audit"
	"notification-platform/internal/event/template"
	"notification-platform/internal/repository"
	"notification-platform/internal/repository/dao"
	"notification-platform/internal/service/audit"
	"notification-platform/internal/service/provider/manage"
	"notification-platform/internal/service/provider/sms/client"
	manage2 "notification-platform/internal/service/template/manage"
	"notification-platform/internal/test/ioc"
	"github.com/confluentinc/confluent-kafka-go/v2/kafka"
)

// Injectors from wire.go:

func Init(providerSvc manage.Service, auditSvc audit.Service, clients map[string]client.Client, producer *kafka.Producer, consumer *kafka.Consumer, batchSize int, batchTimeout time.Duration) (*Service, error) {
	db := ioc.InitDBAndTables()
	channelTemplateDAO := dao.NewChannelTemplateDAO(db)
	channelTemplateRepository := repository.NewChannelTemplateRepository(channelTemplateDAO)
	channelTemplateService := manage2.NewChannelTemplateService(channelTemplateRepository, providerSvc, auditSvc, clients)
	auditResultConsumer, err := template.NewAuditResultConsumer(channelTemplateService, consumer, batchSize, batchTimeout)
	if err != nil {
		return nil, err
	}
	resultCallbackEventProducer, err := audit2.NewResultCallbackEventProducer(producer)
	if err != nil {
		return nil, err
	}
	service := &Service{
		Svc:                 channelTemplateService,
		Repo:                channelTemplateRepository,
		AuditResultConsumer: auditResultConsumer,
		AuditResultProducer: resultCallbackEventProducer,
	}
	return service, nil
}

// wire.go:

type Service struct {
	Svc                 manage2.ChannelTemplateService
	Repo                repository.ChannelTemplateRepository
	AuditResultConsumer *template.AuditResultConsumer
	AuditResultProducer audit2.ResultCallbackEventProducer
}
