// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"notification-platform/internal/repository"
	"notification-platform/internal/repository/dao"
	"notification-platform/internal/service/provider/manage"
	"notification-platform/internal/test/ioc"
)

// Injectors from wire.go:

func Init() manage.Service {
	db := ioc.InitDBAndTables()
	string2 := ioc.InitProviderEncryptKey()
	providerDAO := dao.NewProviderDAO(db, string2)
	providerRepository := repository.NewProviderRepository(providerDAO)
	service := manage.NewProviderService(providerRepository)
	return service
}
