// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"notification-platform/internal/repository"
	"notification-platform/internal/repository/cache/local"
	"notification-platform/internal/repository/cache/redis"
	"notification-platform/internal/repository/dao"
	"notification-platform/internal/service/config"
	"notification-platform/internal/test/ioc"
	"github.com/patrickmn/go-cache"
)

// Injectors from wire.go:

func InitConfigService(localCache *cache.Cache) config.BusinessConfigService {
	db := ioc.InitDBAndTables()
	businessConfigDAO := dao.NewBusinessConfigDAO(db)
	client := ioc.InitRedisClient()
	cache2 := local.NewLocalCache(client, localCache)
	redisCache := redis.NewCache(client)
	businessConfigRepository := repository.NewBusinessConfigRepository(businessConfigDAO, cache2, redisCache)
	businessConfigService := config.NewBusinessConfigService(businessConfigRepository)
	return businessConfigService
}
