// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package notification

import (
	"notification-platform/internal/repository"
	"notification-platform/internal/repository/cache"
	"notification-platform/internal/repository/cache/redis"
	"notification-platform/internal/repository/dao"
	"notification-platform/internal/service/notification"
	"notification-platform/internal/test/ioc"
)

// Injectors from wire.go:

func Init() *Service {
	v := ioc.InitDBAndTables()
	notificationDAO := dao.NewNotificationDAO(v)
	cmdable := ioc.InitRedis()
	quotaCache := redis.NewQuotaCache(cmdable)
	notificationRepository := repository.NewNotificationRepository(notificationDAO, quotaCache)
	service := notification.NewNotificationService(notificationRepository)
	quotaRepository := repository.NewQuotaRepositoryV2(quotaCache)
	callbackLogDAO := dao.NewCallbackLogDAO(v)
	callbackLogRepository := repository.NewCallbackLogRepository(notificationRepository, callbackLogDAO)
	notificationService := &Service{
		Svc:             service,
		QuotaCache:      quotaCache,
		Repo:            notificationRepository,
		QuotaRepo:       quotaRepository,
		CallbackLogRepo: callbackLogRepository,
	}
	return notificationService
}

// wire.go:

type Service struct {
	Svc             notification.NotificationService
	QuotaCache      cache.QuotaCache
	Repo            repository.NotificationRepository
	QuotaRepo       repository.QuotaRepository
	CallbackLogRepo repository.CallbackLogRepository
}
