// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package callback

import (
	"notification-platform/internal/repository"
	"notification-platform/internal/repository/cache/redis"
	"notification-platform/internal/repository/dao"
	"notification-platform/internal/service/config"
	"notification-platform/internal/service/notification/callback"
	"notification-platform/internal/test/ioc"
)

// Injectors from wire.go:

func Init(cnfigSvc config.BusinessConfigService) *Service {
	v := ioc.InitDBAndTables()
	notificationDAO := dao.NewNotificationDAO(v)
	cmdable := ioc.InitRedis()
	quotaCache := redis.NewQuotaCache(cmdable)
	notificationRepository := repository.NewNotificationRepository(notificationDAO, quotaCache)
	callbackLogDAO := dao.NewCallbackLogDAO(v)
	callbackLogRepository := repository.NewCallbackLogRepository(notificationRepository, callbackLogDAO)
	service := callback.NewCallbackService(cnfigSvc, callbackLogRepository)
	quotaRepository := repository.NewQuotaRepositoryV2(quotaCache)
	callbackService := &Service{
		Svc:              service,
		Repo:             callbackLogRepository,
		NotificationRepo: notificationRepository,
		QuotaRepo:        quotaRepository,
	}
	return callbackService
}

// wire.go:

type Service struct {
	Svc              callback.CallbackService
	Repo             repository.CallbackLogRepository
	NotificationRepo repository.NotificationRepository
	QuotaRepo        repository.QuotaRepository
}
